import { Component } from '@angular/core';
import { IonicPage, NavController, NavParams, Platform, AlertController, PopoverController } from 'ionic-angular';
import { PopoverPage } from '../popover/popover';
import { Storage } from '@ionic/storage';

@IonicPage()
@Component({
  selector: 'page-listherb',
  templateUrl: 'listherb.html',
})

export class ListherbPage {
  
  //start hide
  public buttonClicked: boolean = false;
  public buttonClicked2: boolean = true;
  public onButtonClick() {
    this.buttonClicked = !this.buttonClicked;
    this.buttonClicked2 = !this.buttonClicked2;
      console.log("hide n show");
  }
  //done hide

  descending: boolean = false;
  order: number;
  column: string = 'name';

  constructor(public navCtrl: NavController,
              public navParams: NavParams,
              public platform : Platform,
              public alert : AlertController,
              public popoverCtrl : PopoverController,
              public storage : Storage) {

    platform.registerBackButtonAction(() => {this.exit();  console.log("backPressed 1");},1);

    /* this.storage.get('susunan').then((susunan) => {
      if (susunan=='sort') {  this.sort();  }
      if (susunan=='sort2') {  this.sort2();  }
     }); */
    
    //if (this.navParams.get("susunan")=='sort'){ this.sort(); };
    //if (this.navParams.get("susunan")=='sort2'){ this.sort2(); };
    
  }
 

  public tsutsun : any;
  susun() {
    if(this.tsutsun=='huruf'){
    this.sort2();
    }
    else { this.sort(); }
    //pastu try buat condition sini
  }
  /* Baiki sini, aku try guna storage daa  * /
  ionViewWillEnter() {
    this.storage.get('susunan').then((susunan) => {
      if (susunan=='sort') {  this.sort();  }
      if (susunan=='sort2') {  this.sort2();  }
     });
  } */
  
  
  exit(){
    let alert = this.alert.create({
      title: 'Keluar',
      message: 'Anda ingin keluar?',
      buttons: [{
        text: "Keluar?",
        handler: () => { this.exitApp() }
      }, {
        text: "Batal",
        role: 'cancel'
      }]
    })
    alert.present();
}
exitApp(){
  this.platform.exitApp();
}

 /* lists kat sini */
  public lists : Array<any> = [
    { id : 'HOT001-Tongkat Ali',
      imageUrl: 'assets/imgs/herb/HOT0001-Tongkat Ali/HOT0001-1.jpg',
      hot: 'HOT001',
      title: 'Tongkat Ali',
      description: 'Eurycoma longifolia (Jack)'
    },
    { id : 'HOT002-Pegaga',
      imageUrl: 'assets/imgs/herb/HOT0002- Pegaga/HOT0002.jpg',
      hot: 'HOT002',
      title: 'Pegaga',
      description: 'Centella asiatica (L.) Urb.'
    },
    { id : 'HOT003-Misai Kucing',
      imageUrl: 'assets/imgs/herb/HOT0003-Misai Kucing/m1.jpg',
      hot: 'HOT003',
      title: 'Misai Kucing',
      description: 'Orthosiphon stamineus Benth'
    },
    { id : 'HOT004-Halia',
      imageUrl: 'assets/imgs/herb/HOT0004-Halia/HOT0004-1.jpg',
      hot: 'HOT004',
      title: 'Halia',
      description: 'Zingiber officinale Rosc.'
    },
    { id : 'HOT005-Lengkuas',
      imageUrl: 'assets/imgs/herb/HOT0005-Lengkuas/HOT0005-1.jpg',
      hot: 'HOT005',
      title: 'Lengkuas',
      description: 'Alpinia galanga SW'
    },
    { id : 'HOT006-Sireh',
      imageUrl: 'assets/imgs/herb/HOT0006-Sireh/HOT0006-1.jpg',
      hot: 'HOT006',
      title: 'Sireh',
      description: 'Piper betle'
    },
    { id : 'HOT007-Mengkudu Besar',
      imageUrl: 'assets/imgs/herb/HOT0007-Mengkudu Besar/HOT0007-2.jpg',
      hot: 'HOT007',
      title: 'Mengkudu Besar',
      description: 'Morinda citrifolia L.'
    },
    { id : 'HOT008-Mengkudu Kecil',
      imageUrl: 'assets/imgs/herb/HOT0008-Mengkudu Kecil/HOT0082.jpg',
      hot: 'HOT008',
      title: 'Mengkudu Kecil',
      description: 'Morinda elliptica (Hook.f.) Ridl'
    },
    { id : 'HOT009-Sambung Nyawa',
      imageUrl: 'assets/imgs/herb/HOT0009-Sambung Nyawa/HOT0009-2.jpg',
      hot: 'HOT009',
      title: 'Sambung Nyawa',
      description: 'Gynura procumbens (Lour.) Merr. '
    },
    { id : 'HOT010-Temu Lawak',
      imageUrl: 'assets/imgs/herb/HOT0010-Temu Lawak/HOT0010-1.jpg',
      hot: 'HOT010',
      title: 'Temu Lawak',
      description: 'Curcuma xanthorhiza Roxb.'
    },
    { id : 'HOT011-Kunyit',
      imageUrl: 'assets/imgs/herb/HOT0011-Kunyit/HOT0011-1.jpg',
      hot: 'HOT011',
      title: 'Kunyit',
      description: 'Curcuma longa L. '
    },
    { id : 'HOT012-Mas Cotek',
      imageUrl: 'assets/imgs/herb/HOT0012-Mas Cotek/IMG_8042.jpg',
      hot: 'HOT012',
      title: 'Mas Cotek',
      description: 'Ficus deltoidea. (L)'
    },
    { id : 'HOT013-Kapal Terbang',
      imageUrl: 'assets/imgs/herb/HOT0013-Kapal Terbang/HOT0013-1.jpg',
      hot: 'HOT013',
      title: 'Kapal Terbang',
      description: 'Chromolaena odorata '
    },
    { id : 'HOT014-Dukung Anak',
      imageUrl: 'assets/imgs/herb/HOT0014-Dukung Anak/HOT0014-3.jpg',
      hot: 'HOT014',
      title: 'Dukung Anak',
      description: 'Phyllanthus amarus (Schumach)'
    },
    { id : 'HOT015-Peria Katak',
      imageUrl: 'assets/imgs/herb/HOT0015-Peria Katak/HOT0015-3.jpg',
      hot: 'HOT015',
      title: 'Peria Katak',
      description: 'Momordica charantia L.'
    },
    { id : 'HOT016-Serai Makan',
      imageUrl: 'assets/imgs/herb/HOT0016-Serai/HOT0016-3.jpg',
      hot: 'HOT016',
      title: 'Serai Makan',
      description: 'Cymbopogon citratus (DC) Stapf.'
    },
    { id : 'HOT017-Serai Wangi',
      imageUrl: 'assets/imgs/herb/HOT0017-Serai Wangi/HOT0017-1.jpg',
      hot: 'HOT017',
      title: 'Serai Wangi',
      description: 'Cymbopogon nardus (Linne)Rendle'
    },
    { id : 'HOT018-Pinang',
      imageUrl: 'assets/imgs/herb/HOT0018-Pinang/HOT0018-1.jpg',
      hot: 'HOT018',
      title: 'Pinang',
      description: 'Areca catechu L.'
    },
    { id : 'HOT019-Kemangi',
      imageUrl: 'assets/imgs/herb/HOT0019-Selasih/HOT00019-1.jpg',
      hot: 'HOT019',
      title: 'Selasih',
      description: 'Ocimum basilicum L.'
    },
    { id : 'HOT020-Matapelanduk',
      imageUrl: 'assets/imgs/herb/HOT0020-Mata pelanduk/HOT0020-2.jpg',
      hot: 'HOT020',
      title: 'Matapelanduk',
      description: 'Ardisia elliptica Thunb.'
    },
    {
id : 'HOT021-Belalai Gajah',
imageUrl: 'assets/imgs/herb/HOT0021-Belalaigajah/HOT0021-2.jpg',
hot: 'HOT021',
title: 'Belalai Gajah',
description: 'Clinachanthus nutans',
},
{ id : 'HOT022-Keji Beling',
imageUrl: 'assets/imgs/herb/HOT0022-Keji Beling/HOT0022-1.jpg',
hot: 'HOT022',
title: 'Keji Beling',
description: 'Strobilanthus crispus B. L',
},
{ id : 'HOT023-Kari',
imageUrl: 'assets/imgs/herb/HOT0023-Kari/HOT0023-1.jpg',
hot: 'HOT023',
title: 'Kari',
description: 'Murraya koenigli',
},
{ id : 'HOT024-Pandan',
imageUrl: 'assets/imgs/herb/HOT0024-Pandan/HOT0024-1.jpg',
hot: 'HOT024',
title: 'Pandan',
description: 'Pandanus amaryllifolius',
},
{ id : 'HOT025-Pandan Wangi',
imageUrl: 'assets/imgs/herb/HOT0025-Pandan wangi/HOT0025-1.jpg',
hot: 'HOT025',
title: 'Pandan wangi',
description: 'Pandanus odorus',
},
{ id : 'HOT026-Kadok',
imageUrl: 'assets/imgs/herb/HOT0026-Kadok/HOT0026-1.jpg',
hot: 'HOT026',
title: 'Kadok',
description: 'Piper sarmentosum Roxb.',
},
{ id : 'HOT027-Hempedu Bumi',
imageUrl: 'assets/imgs/herb/HOT0027-Hempedu Bumi/HOT0027-1.jpg',
hot: 'HOT027',
title: 'Hempedu Bumi',
description: 'Andrographis paniculata',
},
{ id : 'HOT028-Gandarussa Hitam',
imageUrl: 'assets/imgs/herb/HOT0028-Gandarussa Hitam/HOT0028-1.jpg',
hot: 'HOT028',
title: 'Gandarussa Hitam',
description: 'Justicia gendarussa (Burm.F)',
},
{ id : 'HOT029-Mengkunyit',
imageUrl: 'assets/imgs/herb/HOT0029-Mengkunyit/HOT0029-1.jpg',
hot: 'HOT029',
title: 'Mengkunyit',
description: 'Coscinium fenestratum (Gaertn.) Colebr',
},
{ id : 'HOT030-Tongkat Ali Hitam',
imageUrl: 'assets/imgs/herb/HOT0030-Tongkat Ali Hitam/HOT0030-1.jpg',
hot: 'HOT030',
title: 'Tongkat Ali Hitam',
description: 'Polyalthia bullata King',
},
{ id : 'HOT031-Naga Buana',
imageUrl: 'assets/imgs/herb/HOT0031-Naga Buana/HOT0031-1.jpg',
hot: 'HOT031',
title: 'Naga Buana',
description: 'Phyllanthus pulcher Wull.ex.Mull.Arg',
},
{ id : 'HOT032-Kacip Fatimah',
imageUrl: 'assets/imgs/herb/HOT0032-Kacip fatimah/HOT0032-1.jpg',
hot: 'HOT032',
title: 'Kacip Fatimah',
description: 'Labisia pumila Benth',
},
{ id : 'HOT033-Ulam Raja',
imageUrl: 'assets/imgs/herb/HOT0033-Ulam Raja/HOT0033-1.jpg',
hot: 'HOT033',
title: 'Ulam Raja',
description: 'Cosmos caudatus Kunth',
},
{ id : 'HOT034-Kucing Galak',
imageUrl: 'assets/imgs/herb/HOT0034-Kucing galak/HOT0034-1.jpg',
hot: 'HOT034',
title: 'Kucing Galak',
description: 'Acalypha indica Linn',
},
{ id : 'HOT035-Bangun-Bangun',
imageUrl: 'assets/imgs/herb/HOT0035-Bangun-bangun/HOT0035-1.jpg',
hot: 'HOT035',
title: 'Bangun-bangun',
description: 'Coleus amboinicus Lour',
},
{ id : 'HOT036-Senduduk Putih',
imageUrl: 'assets/imgs/herb/HOT0036-Senduduk putih/HOT0036-1.jpg',
hot: 'HOT036',
title: 'Senduduk Putih',
description: 'Melastoma decemfidum',
},
{ id : 'HOT037-Senduduk Merah',
imageUrl: 'assets/imgs/herb/HOT0037-Senduduk merah/HOT0037-3.jpg',
hot: 'HOT037',
title: 'Senduduk Merah',
description: 'Melastoma malabathricum Linn.',
},
{ id : 'HOT038-Gelenggang Besar',
imageUrl: 'assets/imgs/herb/HOT0038-Gelenggang Besar/HOT0038-1.jpg',
hot: 'HOT038',
title: 'Gelenggang Besar',
description: 'Cassia alata Linn',
},
{ id : 'HOT039-Gelenggang Kecil',
imageUrl: 'assets/imgs/herb/HOT0039-Gelenggang Kecil/HOT0039-1.jpg',
hot: 'HOT039',
title: 'Gelenggang Kecil',
description: 'Casia obtusifolia',
},
{ id : 'HOT040-Patawali',
imageUrl: 'assets/imgs/herb/HOT0040-Patawali/HOT0040-1.jpg',
hot: 'HOT040',
title: 'Patawali',
description: 'Tinospora crispa (Linn.) Mier ex Hook F. & Thorns',
},
{ id : 'HOT041-Kantan',
imageUrl: 'assets/imgs/herb/HOT0041-Kantan/HOT0041-1.jpg',
hot: 'HOT041',
title: 'Kantan',
description: 'Etlingera elatior',
},
{ id : 'HOT042-Letup-Letup',
imageUrl: 'assets/imgs/herb/HOT0042-Letup-letup/HOT0042-1.jpg',
hot: 'HOT042',
title: 'Letup-letup',
description: 'Physalis minima Linn.',
},
{ id : 'HOT043-Lempoyang',
imageUrl: 'assets/imgs/herb/HOT0043-Lempoyang/HOT0043-1.jpg',
hot: 'HOT043',
title: 'Lempoyang',
description: 'Zingerber zerumbet L.',
},
{ id : 'HOT044-Tea Tree',
imageUrl: 'assets/imgs/herb/HOT0044-Tea tree/HOT0044-1.jpg',
hot: 'HOT044',
title: 'Tea tree',
description: 'Melaleuca alternifolia',
},
{ id : 'HOT045-Cucur Atap',
imageUrl: 'assets/imgs/herb/HOT0045-Cucur Atap/HOT0045-3.jpg',
hot: 'HOT045',
title: 'Cucur atap',
description: 'Baeckea frutescens L.',
},
{ id : 'HOT046-Gelam',
imageUrl: 'assets/imgs/herb/HOT0046-Gelam/HOT0046-1.jpg',
hot: 'HOT046',
title: 'Gelam',
description: 'Melaleuca cajaputi Powell.',
},
{ id : 'HOT047-Rosel',
imageUrl: 'assets/imgs/herb/HOT0047-Rosel/HOT0047-1.jpg',
hot: 'HOT047',
title: 'Rosel',
description: 'Hibiscus sabdariffa',
},
{ id : 'HOT048-Limau Purut',
imageUrl: 'assets/imgs/herb/HOT0048-Limau Purut/HOT0048-1.JPG',
hot: 'HOT048',
title: 'Limau Purut',
description: 'Citrus hystrix D. C',
},
{ id : 'HOT049-Limau Nipis',
imageUrl: 'assets/imgs/herb/HOT0049-Limau Nipis/HOT0049-3.JPG',
hot: 'HOT049',
title: 'Limau Nipis',
description: 'Citrus aurantifolia (Cristm.) Swingle',
},
{ id : 'HOT050-Limau Kasturi',
imageUrl: 'assets/imgs/herb/HOT0050-Limau Kasturi/HOT0050-1.jpg',
hot: 'HOT050',
title: 'Limau Kasturi',
description: 'Citrus microcarpa Bunge',
},
{ id : 'HOT051-Kesum',
imageUrl: 'assets/imgs/herb/HOT0051-Kesum/HOT0051-1.jpg',
hot: 'HOT051',
title: 'Kesum',
description: 'Polygonum minus Huds',
},
{ id : 'HOT052-Kenanga',
imageUrl: 'assets/imgs/herb/HOT0052-Kenanga/HOT0052-1.jpg',
hot: 'HOT052',
title: 'Kenanga',
description: 'Cananga odorata Hook. F. & Thomson',
},
{ id : 'HOT053-Pucuk Manis',
imageUrl: 'assets/imgs/herb/HOT0053-Pucuk Manis/HOT0053-1.jpg',
hot: 'HOT053',
title: 'Pucuk Manis',
description: 'Sauropus androgynus (L.) Merr.',
},
{ id : 'HOT054-Cekur',
imageUrl: 'assets/imgs/herb/HOT0054-Cekur/HOT0054-1.jpg',
hot: 'HOT054',
title: 'Cekur',
description: 'Kaempferia galanga L.',
},
{ id : 'HOT055-Serai Kayu',
imageUrl: 'assets/imgs/herb/HOT0055-Serai Kayu/HOT0055-2.JPG',
hot: 'HOT055',
title: 'Serai kayu',
description: 'Syzygium polyanthum',
},
{ id : 'HOT056-Putat',
imageUrl: 'assets/imgs/herb/HOT0056-Putat/HOT0056-1.jpg',
hot: 'HOT056',
title: 'Putat',
description: 'Barringtonia racemosa',
},
{ id : 'HOT057-Lemuni Putih',
imageUrl: 'assets/imgs/herb/HOT0057-Lemuni Putih/HOT0057-1.jpg',
hot: 'HOT057',
title: 'Lemuni Putih',
description: 'Vitex trifolia',
},
{ id : 'HOT058-Lemuni Hitam',
imageUrl: 'assets/imgs/herb/HOT0058-Lemuni Hitam/HOT0058-1.jpg',
hot: 'HOT058',
title: 'Lemuni Hitam',
description: 'Vitex negundo',
},
{ id : 'HOT059-Belimbing Buluh',
imageUrl: 'assets/imgs/herb/HOT0059-Belimbing Buluh/HOT0059-1.jpg',
hot: 'HOT059',
title: 'Belimbing Buluh',
description: 'Averrhoa bilimbi',
},
{ id : 'HOT060-Belimbing Besi',
imageUrl: 'assets/imgs/herb/HOT0060-Belimbing besi/HOT0060-1.jpg',
hot: 'HOT060',
title: 'Belimbing Besi',
description: 'Averrhoa carambola L.',
},
{ id : 'HOT061-Belimbing Tanah',
imageUrl: 'assets/imgs/herb/HOT0061-Belimbing Tanah/HOT0061-1.jpg',
hot: 'HOT061',
title: 'Belimbing Tanah',
description: 'Oxalis barrelieri L.',
},
{ id : 'HOT062-Kemunting Cina',
imageUrl: 'assets/imgs/herb/HOT0062-Kemunting Cina/HOT0062-1.jpg',
hot: 'HOT062',
title: 'Kemunting Cina',
description: 'Catharathus roseus',
},
{ id : 'HOT063-Kemunting',
imageUrl: 'assets/imgs/herb/HOT0063-Kemunting/HOT0063-1.JPG',
hot: 'HOT063',
title: 'Kemunting',
description: 'Rhodomyrtus tormentosa',
},
{ id : 'HOT064-Cempaka',
imageUrl: 'assets/imgs/herb/HOT0064-Cempaka/HOT0064-1.jpg',
hot: 'HOT064',
title: 'Cempaka',
description: 'Michelia champaca',
},
{ id : 'HOT065-Cina Maki',
imageUrl: 'assets/imgs/herb/HOT0065-Cina Maki/HOT0065-1.jpg',
hot: 'HOT065',
title: 'Cina Maki',
description: 'Leptospermum flavescens',
},
{ id : 'HOT066-Cermai',
imageUrl: 'assets/imgs/herb/HOT0066-Cermai/HOT0066-1.jpg',
hot: 'HOT066',
title: 'Cermai',
description: 'Phyllanthus acidus',
},
{ id : 'HOT067-Delima',
imageUrl: 'assets/imgs/herb/HOT0067-Delima/HOT0067-1.jpg',
hot: 'HOT067',
title: 'Delima',
description: 'Punica granatum',
},
{ id : 'HOT068-Nona',
imageUrl: 'assets/imgs/herb/HOT0068-Nona/HOT0068-1.jpg',
hot: 'HOT068',
title: 'Nona',
description: 'Annona reticulata',
},
{ id : 'HOT069-Gajus',
imageUrl: 'assets/imgs/herb/HOT0069-Gajus/HOT0069-1.jpg',
hot: 'HOT069',
title: 'Gajus',
description: 'Anacardium occidentale',
},
{ id : 'HOT070-Jambu Batu',
imageUrl: 'assets/imgs/herb/HOT0070-Jambu Batu/HOT0070-2.JPG',
hot: 'HOT070',
title: 'Jambu Batu',
description: 'Psidium guajava',
},
{ id : 'HOT071-Durian Belanda',
imageUrl: 'assets/imgs/herb/HOT0071-Durian Belanda/HOT0071-1.jpg',
hot: 'HOT071',
title: 'Durian Belanda',
description: 'Annona muricata',
},
{ id : 'HOT072-Jarak',
imageUrl: 'assets/imgs/herb/HOT0072-Jarak/HOT0072-1.jpg',
hot: 'HOT072',
title: 'Jarak',
description: 'Ricinus communis Linn',
},
{ id : 'HOT073-Bunga Raya Putih',
imageUrl: 'assets/imgs/herb/HOT0073-Bunga Raya (Putih)/HOT0073-1.jpg',
hot: 'HOT073',
title: 'Bunga Raya (Putih)',
description: 'Hibiscus rosa sinensis Linn.',
},
{ id : 'HOT074-Ekor Kucing',
imageUrl: 'assets/imgs/herb/HOT0074-Ekor Kucing/HOT0074-1.jpg',
hot: 'HOT074',
title: 'Ekor kucing',
description: 'Acalypha hispida Burm f.',
},
{ id : 'HOT075-Ekor Anjing',
imageUrl: 'assets/imgs/herb/HOT0075-Ekor Anjing/HOT0075-1.jpg',
hot: 'HOT075',
title: 'Ekor Anjing',
description: 'Plantagor major',
},
{ id : 'HOT076-Kayu Manis',
imageUrl: 'assets/imgs/herb/HOT0076-Kayu manis/HOT0076-1.jpg',
hot: 'HOT076',
title: 'Kayu manis',
description: 'Cinnamomum verum',
},
{ id : 'HOT077-Cengkih',
imageUrl: 'assets/imgs/herb/HOT0077-Cengkih/HOT0077-1.jpg',
hot: 'HOT077',
title: 'Cengkih',
description: 'Syzygium aromaticum',
},
{ id : 'HOT078-Halba',
imageUrl: 'assets/imgs/herb/HOT0078-Halba/HOT0078-1.jpg',
hot: 'HOT078',
title: 'Halba',
description: 'Trigonella foenum-graecum',
},
{ id : 'HOT079-Bunga Lawang',
imageUrl: 'assets/imgs/herb/HOT0079-Bunga Lawang/HOT0079-1.jpg',
hot: 'HOT079',
title: 'Bunga Lawang',
description: 'Illicium verum Hook',
},
{ id : 'HOT080-Jerangau',
imageUrl: 'assets/imgs/herb/HOT0080-Jerangau/HOT0080-1.JPG',
hot: 'HOT080',
title: 'Jerangau',
description: 'Acarus calamus L.',
},
{ id : 'HOT081-Tenggek Burung',
imageUrl: 'assets/imgs/herb/HOT0081-Tenggek Burung/HOT0081-1.jpg',
hot: 'HOT081',
title: 'Tenggek Burung',
description: 'Melicope ptelefolia Champ. ex Benth',
},
{ id : 'HOT082-Bunga Melor',
imageUrl: 'assets/imgs/herb/HOT0082-Bunga Melor/HOT0082-1.jpg',
hot: 'HOT082',
title: 'Bunga Melor',
description: 'Jasminum sambac',
},
{ id : 'HOT083-Beluntas',
imageUrl: 'assets/imgs/herb/HOT0083-Beluntas/HOT0083-1.jpg',
hot: 'HOT083',
title: 'Beluntas',
description: 'Pluchea indica',
},
{ id : 'HOT084-Asam Gelugor',
imageUrl: 'assets/imgs/herb/HOT0084-Asam Gelugor/HOT0084-1.jpg',
hot: 'HOT084',
title: 'Asam Gelugor',
description: 'Garcinia atroviridis Griff.',
},
{ id : 'HOT085-Aji Samad',
imageUrl: 'assets/imgs/herb/HOT0085-Aji Samad/HOT0085-1.jpg',
hot: 'HOT085',
title: 'Aji Samad',
description: 'Prismatomeris tetrandra',
},
{ id : 'HOT086-Bawang Merah',
imageUrl: 'assets/imgs/herb/HOT0086-Bawang merah/HOT0086-1.jpg',
hot: 'HOT086',
title: 'Bawang merah',
description: 'Allium cepa var. aggregatum',
},
{ id : 'HOT087-Bawah Putih',
imageUrl: 'assets/imgs/herb/HOT0087-Bawah putih/HOT0087-1.jpg',
hot: 'HOT087',
title: 'Bawah putih',
description: 'Allium sativum L.',
},
{ id : 'HOT088-Bunga Tanjung',
imageUrl: 'assets/imgs/herb/HOT0088-Bunga Tanjung/HOT0088-1.jpg',
hot: 'HOT088',
title: 'Bunga Tanjung',
description: 'Mimusop elengi (L.)',
},
{ id : 'HOT089-Mahkota Dewa',
imageUrl: 'assets/imgs/herb/HOT0089-Mahkota Dewa/HOT0089-1.jpg',
hot: 'HOT089',
title: 'Mahkota Dewa',
description: 'Phaleria macrocarpa (Scheff.) Boerl',
},
{ id : 'HOT090-Katak Puru',
imageUrl: 'assets/imgs/herb/HOT0090-Katak puru/HOT0090-1.jpg',
hot: 'HOT090',
title: 'Katak Puru',
description: 'Cynometra cauliflora',
},
{ id : 'HOT091-Gajah Beranak',
imageUrl: 'assets/imgs/herb/HOT0091-Gajah Beranak/HOT0091-1.jpg',
hot: 'HOT091',
title: 'Gajah Beranak',
description: 'Goniothalamus macrophyllus',
},
{ id : 'HOT092-Halban',
imageUrl: 'assets/imgs/herb/HOT0092-Halban/HOT0092-1.jpg',
hot: 'HOT092',
title: 'Halban',
description: 'Vitex pubescens Vahl',
},
{ id : 'HOT093-Halia Kesing',
imageUrl: 'assets/imgs/herb/HOT0093-Halia Kesing/HOT0093-1.jpg',
hot: 'HOT093',
title: 'Halia Kesing',
description: 'Elettariopsis curtisii (Baker)',
},
{ id : 'HOT094-Inai',
imageUrl: 'assets/imgs/herb/HOT0094-Inai/HOT0094-1.jpg',
hot: 'HOT094',
title: 'Inai',
description: 'Lawsonia inermis L.',
},
{ id : 'HOT095-Jarum Tujuh Bilah',
imageUrl: 'assets/imgs/herb/HOT0095-Jarum Tujuh Bilah/HOT0095-1.jpg',
hot: 'HOT095',
title: 'Jarum Tujuh Bilah',
description: 'Pereskia sacharosa Griseb.',
},
{ id : 'HOT096-Kulim',
imageUrl: 'assets/imgs/herb/HOT0096-Kulim/HOT0096-1.jpg',
hot: 'HOT096',
title: 'Kulim',
description: 'Scorodocarpus borneensis',
},
{ id : 'HOT097-Kedondong',
imageUrl: 'assets/imgs/herb/HOT0097-Kedondong/HOT0097-1.jpg',
hot: 'HOT097',
title: 'Kedondong',
description: 'Spondias dulcis (Syn. Spondias cytherea)',
},
{ id : 'HOT098-Jintan Hitam',
imageUrl: 'assets/imgs/herb/HOT0098-Jintan hitam/HOT0098-1.jpg',
hot: 'HOT098',
title: 'Jintan Hitam',
description: 'Nigella sativa',
},
{ id : 'HOT099-Kacang Telang',
imageUrl: 'assets/imgs/herb/HOT0099-Kacang Telang/HOT0099-1.jpg',
hot: 'HOT099',
title: 'Kacang Telang',
description: 'Clitoria ternatea',
},
{ id : 'HOT100-Terung Pipit',
imageUrl: 'assets/imgs/herb/HOT0100-Terung Pipit/HOT0100-1.jpg',
hot: 'HOT100',
title: 'Terung Pipit',
description: 'Solanum torvum Swartz',
},
{ id : 'HOT101-Lada Hitam',
imageUrl: 'assets/imgs/herb/HOT0101-Lada Hitam/HOT0101-1.jpg',
hot: 'HOT101',
title: 'Lada Hitam',
description: 'Piper nigrum',
},
{ id : 'HOT102-Kelapa',
imageUrl: 'assets/imgs/herb/HOT0102-Kelapa/HOT0102-1.jpg',
hot: 'HOT102',
title: 'Kelapa',
description: 'Cocos nucifera',
},
{ id : 'HOT103-Setawar',
imageUrl: 'assets/imgs/herb/HOT0103-Setawar/HOT0103-1.jpg',
hot: 'HOT103',
title: 'Setawar',
description: 'Kalanchoe pinnata',
},
{ id : 'HOT104-Sundal Malam',
imageUrl: 'assets/imgs/herb/HOT0104-Sundal Malam/HOT0104-1.jpg',
hot: 'HOT104',
title: 'Sundal Malam',
description: 'Polianthes tuberosa L.',
},
{ id : 'HOT105-Medang Teja',
imageUrl: 'assets/imgs/herb/HOT0105-Medang Teja/HOT0105-1.jpg',
hot: 'HOT105',
title: 'Medang Teja',
description: 'Cinnamomum iners',
},
{ id : 'HOT106-Ubi Jaga',
imageUrl: 'assets/imgs/herb/HOT0106-Ubi Jaga/HOT0106-1.jpg',
hot: 'HOT106',
title: 'Ubi Jaga',
description: 'Smilax myosotiflora',
},
{ id : 'HOT107-Petai',
imageUrl: 'assets/imgs/herb/HOT0107-Petai/HOT0107-1.jpg',
hot: 'HOT107',
title: 'Petai',
description: 'Parkia speciosa Hassk',
},
{ id : 'HOT108-Petai Belalang',
imageUrl: 'assets/imgs/herb/HOT0108-Petai Belalang/HOT0108-1.jpg',
hot: 'HOT108',
title: 'Petai belalang',
description: 'Leucaena leucocephala (Lam.) de Wit.',
},
{ id : 'HOT109-Manggis',
imageUrl: 'assets/imgs/herb/HOT0109-Manggis/HOT0109-1.jpg',
hot: 'HOT109',
title: 'Manggis',
description: 'Garcinia mangostana L.',
},
{ id : 'HOT110-Markisa',
imageUrl: 'assets/imgs/herb/HOT0110-Markisa/HOT0110-1.jpg',
hot: 'HOT110',
title: 'Markisa',
description: 'Passiflora edulis Sims.',
},
{ id : 'HOT111-Betik',
imageUrl: 'assets/imgs/herb/HOT0111-Betik/HOT0111-1.jpg',
hot: 'HOT111',
title: 'Betik',
description: 'Carica papaya Linn',
},
{ id : 'HOT112-Capa',
imageUrl: 'assets/imgs/herb/HOT0112-Capa/HOT0112-1.jpg',
hot: 'HOT112',
title: 'Capa',
description: 'Blumea balsamifera L.',
},
{ id : 'HOT113-Ciku',
imageUrl: 'assets/imgs/herb/HOT0113-Ciku/HOT0113-1.jpg',
hot: 'HOT113',
title: 'Ciku',
description: 'Manilkara zapota (L.) Van Royen',
},
{ id : 'HOT114-Pokok ajaib',
imageUrl: 'assets/imgs/herb/HOT0114-Pokok ajaib/HOT0114-1.jpg',
hot: 'HOT114',
title: 'Pokok ajaib',
description: 'Synsepalum dulcificum',
},
{ id : 'HOT115-Kecubong',
imageUrl: 'assets/imgs/herb/HOT0115-Kecubong/HOT0115-1.jpg',
hot: 'HOT115',
title: 'Kecubong',
description: 'Datura metel (L)',
},
{ id : 'HOT116-Nangka',
imageUrl: 'assets/imgs/herb/HOT0116-Nangka/HOT0116-1.jpg',
hot: 'HOT116',
title: 'Nangka',
description: 'Artocarpus heterophyllus Lam',
},
{ id : 'HOT117-Periuk Kera',
imageUrl: 'assets/imgs/herb/HOT0117-Periuk Kera/HOT0117-1.jpg',
hot: 'HOT117',
title: 'Periuk Kera',
description: 'Nepenthes ampullaria',
},
{ id : 'HOT118-Ketumbar',
imageUrl: 'assets/imgs/herb/HOT0118-Ketumbar/HOT0118-1.jpg',
hot: 'HOT118',
title: 'Ketumbar',
description: 'Coriandrum sativum',
},
{ id : 'HOT119-Jintan/Cumin',
imageUrl: 'assets/imgs/herb/HOT0119-Jintan/HOT0119-1.jpg',
hot: 'HOT119',
title: 'Jintan/Cumin',
description: 'Cuminum cyminum',
},
{ id : 'HOT120-Kangkung',
imageUrl: 'assets/imgs/herb/HOT0120-Kangkung/HOT0120-1.jpg',
hot: 'HOT120',
title: 'Kangkung',
description: 'Ipomoea aquatica',
},
{ id : 'HOT121-Lidah Buaya',
imageUrl: 'assets/imgs/herb/HOT0121-Lidah Buaya/HOT0121-1.jpg',
hot: 'HOT121',
title: 'Lidah Buaya',
description: 'Aloe vera (L) Burm.f',
},
{ id : 'HOT122-Kunyit Hitam',
imageUrl: 'assets/imgs/herb/HOT0122-Kunyit Hitam/HOT0122-1.jpg',
hot: 'HOT122',
title: 'Kunyit Hitam',
description: 'Curcuma caesia Roxb.',
},
{ id : 'HOT123-Lemba',
imageUrl: 'assets/imgs/herb/HOT0123-Lemba/HOT0123-1.jpg',
hot: 'HOT123',
title: 'Lemba',
description: 'Curculigo latifolia',
},
{ id : 'HOT124-Lemon',
imageUrl: 'assets/imgs/herb/HOT0124-Lemon/HOT0124-1.jpg',
hot: 'HOT124',
title: 'Lemon',
description: 'Citrus limon',
},
{ id : 'HOT125-Semambu',
imageUrl: 'assets/imgs/herb/HOT0125-Semambu/HOT0125-1.jpg',
hot: 'HOT125',
title: 'Semambu/Neem',
description: 'Azadirachta indica',
},
{ id : 'HOT126-Nilam',
imageUrl: 'assets/imgs/herb/HOT0126-Nilam/HOT0126-1.jpg',
hot: 'HOT126',
title: 'Nilam',
description: 'Pogostemon cablin Benth',
},
{ id : 'HOT127-Palas',
imageUrl: 'assets/imgs/herb/HOT0127-Palas/HOT0127-1.jpg',
hot: 'HOT127',
title: 'Palas',
description: 'Licuala spinosa Roxb.',
},
{ id : 'HOT128-Temu Mangga',
imageUrl: 'assets/imgs/herb/HOT0128-Temu Mangga/HOT0128-1.jpg',
hot: 'HOT128',
title: 'Temu Mangga',
description: 'Curcuma amada Roxb',
},
{ id : 'HOT129-Tapak Sulaiman',
imageUrl: 'assets/imgs/herb/HOT0129-Tapak Sulaiman/HOT0129-1.jpg',
hot: 'HOT129',
title: 'Tapak Sulaiman',
description: 'Elephantopus scaber L.',
},
{ id : 'HOT130-Jering',
imageUrl: 'assets/imgs/herb/HOT0130-Jering/HOT0130-1.jpg',
hot: 'HOT130',
title: 'Jering',
description: 'Archidendron jiringa (Jack) Nielsen',
},
{ id : 'HOT131-Keladi Ekor Tikus',
imageUrl: 'assets/imgs/herb/HOT0131-Keladi Ekor Tikus/HOT0131-1.jpg',
hot: 'HOT131',
title: 'Keladi Ekor Tikus',
description: 'Archidendron jiringa (Jack) Nielsen',
}, 
/* ************************************************************************* */
/* ************************************************************************* */
/* ************************************************************************* */
/* ************************************************************************* */
{ id : 'HOT132-Keladi Kemoyang',
imageUrl: 'assets/imgs/herb/HOT0132-Keladi Kemoyang/HOT0132-1.jpg',
hot: 'HOT132',
title: 'Keladi Kemoyang',
description: 'Homalomena sagittifolia (Jungh.ex Schott)',
},
{ id : 'HOT133-Keladi Murai',
imageUrl: 'assets/imgs/herb/HOT0133-Keladi Murai/HOT0133-1.jpg',
hot: 'HOT133',
title: 'Keladi Murai',
description: 'Tacca integrifoliab (Ker. Gawl)',
},
{ id : 'HOT134-Kemangi',
imageUrl: 'assets/imgs/herb/HOT0134-Kemangi/HOT0134-1.jpg',
hot: 'HOT134',
title: 'Kemangi',
description: 'Occimum gratissimun',
},
{ id : 'HOT135-Kemboja',
imageUrl: 'assets/imgs/herb/HOT0135-Kemboja/HOT0135-1.jpg',
hot: 'HOT135',
title: 'Kemboja',
description: 'Plumeria rubra Linn.',
},
{ id : 'HOT136-Lalang',
imageUrl: 'assets/imgs/herb/HOT0136-Lalang/HOT0136-1.jpg',
hot: 'HOT136',
title: 'Lalang',
description: 'Imperata cylindrica L.',
},
{ id : 'HOT137-Pulai',
imageUrl: 'assets/imgs/herb/HOT0137-Pulai/HOT0137-1.jpg',
hot: 'HOT137',
title: 'Pulai',
description: 'Alstonia angustiloba (Mig)',
},
{ id : 'HOT138-Melaka',
imageUrl: 'assets/imgs/herb/HOT0138-Melaka/HOT0138-1.jpg',
hot: 'HOT138',
title: 'Melaka',
description: 'Phyllanthus emblica',
},
{ id : 'HOT139-Kopi',
imageUrl: 'assets/imgs/herb/HOT0139-Kopi/HOT0139-1.jpg',
hot: 'HOT139',
title: 'Kopi',
description: 'Coffea robusta',
},
{ id : 'HOT140-Teh',
imageUrl: 'assets/imgs/herb/HOT0140-Teh/HOT0140-1.jpg',
hot: 'HOT140',
title: 'Teh',
description: 'Camellia sinensis (L.) Kuntze',
},
{ id : 'HOT141-Ketum',
imageUrl: 'assets/imgs/herb/HOT0141-Ketum/HOT0141-1.jpg',
hot: 'HOT141',
title: 'Ketum',
description: 'Mitragyna speciosa Korth.',
},
{ id : 'HOT142-Duku',
imageUrl: 'assets/imgs/herb/HOT0142-Duku/HOT0142-1.jpg',
hot: 'HOT142',
title: 'Duku',
description: 'Lansium domesticum Corr var. domesticum',
},
{ id : 'HOT143-Cempedak',
imageUrl: 'assets/imgs/herb/HOT0143-Cempedak/HOT0143-1.jpg',
hot: 'HOT143',
title: 'Cempedak',
description: 'Artocarpus champeden Spreng',
},
{ id : 'HOT144-Langsat',
imageUrl: 'assets/imgs/herb/HOT0144-Langsat/HOT0144-1.jpg',
hot: 'HOT144',
title: 'Langsat',
description: 'Lansium parasiticum Jack',
},
{ id : 'HOT145-Mata Ayam',
imageUrl: 'assets/imgs/herb/HOT0145-Mata Ayam/HOT0145-1.jpg',
hot: 'HOT145',
title: 'Mata Ayam',
description: 'Ardisia crispa',
},
{ id : 'HOT146-Pulut-pulut',
imageUrl: 'assets/imgs/herb/HOT0146-Pulut-pulut/HOT0146-1.jpg',
hot: 'HOT146',
title: 'Pulut-pulut',
description: 'Urena lobata L. Synonyms:Urena americana L. f.; Urena chinensis Osbeck; Urena diversifolia Schumach.; Urena grandiflora DC.; Urena monopetala Lour.; Urena reticulata Cav.; Urena scabriuscula DC.;',
},
{ id : 'HOT147-Kelo/murunggai',
imageUrl: 'assets/imgs/herb/HOT0147-Kelo/murunggai/HOT0147-1.jpg',
hot: 'HOT147',
title: 'Kelo/murunggai',
description: '"Moringa oleifera Lam. Synonyms: Guilandina moringa L.;Hyperanthera moringa (L.) Vahl;Moringa pterygosperma Gaertn. nom. illeg."',
},
{ id : 'HOT148-Teratai',
imageUrl: 'assets/imgs/herb/HOT0148-Teratai/HOT0148-1.jpg',
hot: 'HOT148',
title: 'Teratai',
description: 'Nelumbo nucifera Gaertn',
},
{ id : 'HOT149-Tetulang',
imageUrl: 'assets/imgs/herb/HOT0149-Tetulang/HOT0149-1.jpg',
hot: 'HOT149',
title: 'Tetulang',
description: 'Euphorbia tirucalli. Synonym: Euphorbia neriifolia L.',
},
{ id : 'HOT150-Bunga Tahi Ayam',
imageUrl: 'assets/imgs/herb/HOT0150-Bunga Tahi Ayam/HOT0150-1.jpg',
hot: 'HOT150',
title: 'Bunga Tahi Ayam',
description: '"Lantana camara. Synonym: Camara vulgaris Benth.;Lantana aculeata L.;Lantana armata Schauer; Lantana scabrida Sol.;Lantana tiliifolia Cham"',
},
{ id : 'HOT151-Buah Pelaga',
imageUrl: 'assets/imgs/herb/HOT0151-Buah Pelaga/HOT0151-1.jpg',
hot: 'HOT151',
title: 'Buah Pelaga',
description: 'Amomum elettaria. Synonym: Elettaria cardamomum Maton',
},
{ id : 'HOT152-mulberi',
imageUrl: 'assets/imgs/herb/HOT0152-mulberi/HOT0152-1.jpg',
hot: 'HOT152',
title: 'mulberi',
description: 'Morus alba L.',
},
{ id : 'HOT153-pala',
imageUrl: 'assets/imgs/herb/HOT0153-pala/HOT0153-1.jpg',
hot: 'HOT153',
title: 'pala',
description: 'Myristica fragrans Houtt.',
},
{ id : 'HOT154-Buah keras',
imageUrl: 'assets/imgs/herb/HOT0154-Buah keras/HOT0154-1.jpg',
hot: 'HOT154',
title: 'Buah keras',
description: 'Aleurites moluccana (L.) Wild',
},
{ id : 'HOT155-Galak Tua',
imageUrl: 'assets/imgs/herb/HOT0155-Galak Tua/HOT0155-1.jpg',
hot: 'HOT155',
title: 'Galak Tua',
description: 'Stemona tuberosa. Synonym: Stemona minor Hook f.',
},
{ id : 'HOT156-Medinilla',
imageUrl: 'assets/imgs/herb/HOT0156-Medinilla/HOT0156-1.jpg',
hot: 'HOT156',
title: 'Medinilla',
description: 'Medinilla speciosa',
},
{ id : 'HOT157-Jarak',
imageUrl: 'assets/imgs/herb/HOT0157-Jarak/HOT0157-1.jpg',
hot: 'HOT157',
title: 'Jarak',
description: 'Jatropha curcas L.',
},
{ id : 'HOT158-Ara Tanah',
imageUrl: 'assets/imgs/herb/HOT0158-Ara Tanah/HOT0158-1.jpg',
hot: 'HOT158',
title: 'Ara Tanah',
description: 'Euphorbia hirta L.',
},
{ id : 'HOT159-Cakar Ayam',
imageUrl: 'assets/imgs/herb/HOT0159-Cakar Ayam/HOT0159-1.jpg',
hot: 'HOT159',
title: 'Cakar Ayam',
description: 'Selaginella doederleinii',
},
{ id : 'HOT160-Pokok Duit-duit',
imageUrl: 'assets/imgs/herb/HOT0160-Pokok Duit-duit/HOT0160-1.jpg',
hot: 'HOT160',
title: 'Pokok Duit-duit',
description: 'Pyrrosia piloselloides (L.) M.G. Price',
},
{ id : 'HOT161-Sukai',
imageUrl: 'assets/imgs/herb/HOT0161-Sukai/HOT0161-1.jpg',
hot: 'HOT161',
title: 'Sukai',
description: 'Peronema canescens',
},
{ id : 'HOT162-Keladi Lekir',
imageUrl: 'assets/imgs/herb/HOT0162-Keladi Lekir/HOT0162-1.jpg',
hot: 'HOT162',
title: 'Keladi Lekir',
description: 'Amorphophallus paeoniifolius',
},
{ id : 'HOT163-Keembong',
imageUrl: 'assets/imgs/herb/HOT0163-Keembong/HOT0163-1.jpg',
hot: 'HOT163',
title: 'Keembong',
description: 'Impatiens balsamina',
},
{ id : 'HOT164-Bawang Bakong/tembaga',
imageUrl: 'assets/imgs/herb/HOT0164-Bawang Bakong/tembaga/HOT0164-1.jpg',
hot: 'HOT164',
title: 'Bawang Bakong/tembaga',
description: 'Crynum asiaticum L',
},
{ id : 'HOT165-Kedondong laut',
imageUrl: 'assets/imgs/herb/HOT0165-kdd/HOT0165-1.jpg',
hot: 'HOT165',
title: 'Kedondong laut/daun Belangkas',
description: 'Polyscias fruticosa',
},
{ id : 'HOT166-Gadum',
imageUrl: 'assets/imgs/herb/HOT0166-Gadum/HOT0166-1.jpg',
hot: 'HOT166',
title: 'Gadum',
description: 'Dioscorea hispida. (Den)',
},
{ id : 'HOT167-Kiambang',
imageUrl: 'assets/imgs/herb/HOT0167-Kiambang/HOT0167-1.jpg',
hot: 'HOT167',
title: 'Kiambang',
description: 'Pistia stratiotes',
},
{ id : 'HOT168-pokok lelipan',
imageUrl: 'assets/imgs/herb/HOT0168-pokok lelipan/HOT0168-1.jpg',
hot: 'HOT168',
title: 'pokok lelipan',
description: 'Pedilanthus tithymaloides',
},
{ id : 'HOT169-Bidara',
imageUrl: 'assets/imgs/herb/HOT0169-Bidara/HOT0169-1.jpg',
hot: 'HOT169',
title: 'Bidara',
description: 'Ziziphus mauritiana',
},
{ id : 'HOT170-Selom',
imageUrl: 'assets/imgs/herb/HOT0170-Selom/HOT0170-1.jpg',
hot: 'HOT170',
title: 'Selom',
description: 'Oenanthe javanica',
},
{ id : 'HOT171-Jemuju',
imageUrl: 'assets/imgs/herb/HOT0171-Jemuju/HOT0171-1.jpg',
hot: 'HOT171',
title: 'Jemuju',
description: 'Eryngium foetidum L.',
},
{ id : 'HOT172-Mahagoni',
imageUrl: 'assets/imgs/herb/HOT0172-Mahagoni/HOT0172-1.jpg',
hot: 'HOT172',
title: 'Mahagoni',
description: 'Swietenia macrophylla',
},
{ id : 'HOT173-Machang',
imageUrl: 'assets/imgs/herb/HOT0173-Machang/HOT0173-1.jpg',
hot: 'HOT173',
title: 'Machang',
description: 'Mangifera foetida',
},
{ id : 'HOT174-Akar Jejulung',
imageUrl: 'assets/imgs/herb/HOT0174-Akar Jejulung/HOT0174-1.jpg',
hot: 'HOT174',
title: 'Akar Jejulung',
description: 'Ancistrocladus tectorius Lour',
},
{ id : 'HOT175-Derhaka Mertua',
imageUrl: 'assets/imgs/herb/HOT0175-Derhaka Mertua/HOT0175-1.jpg',
hot: 'HOT175',
title: 'Derhaka Mertua',
description: 'Peliosanthes teta (Andrews)',
},
{ id : 'HOT176-Alek Besi',
imageUrl: 'assets/imgs/herb/HOT0176-Alek Besi/HOT0176-1.jpg',
hot: 'HOT176',
title: 'Alek Besi',
description: 'Smilax spp.',
},
{ id : 'HOT177-Alek Tembaga',
imageUrl: 'assets/imgs/herb/HOT0177-Alek Tembaga/HOT0177-1.jpg',
hot: 'HOT177',
title: 'Alek Tembaga',
description: 'Smilax calophylla (Wall.)',
},
{ id : 'HOT178-Asam Jawa',
imageUrl: 'assets/imgs/herb/HOT0178-Asam Jawa/HOT0178-1.jpg',
hot: 'HOT178',
title: 'Asam Jawa',
description: 'Tamarindus indica L.',
},
{ id : 'HOT179-Batu Pelir Kambing',
imageUrl: 'assets/imgs/herb/HOT0179-Batu Pelir Kambing/HOT0179-1.jpg',
hot: 'HOT179',
title: 'Batu Pelir Kambing',
description: 'Rouvolfia verticillata (Lour) Baill',
},
{ id : 'HOT180-Bayur',
imageUrl: 'assets/imgs/herb/HOT0180-Bayur/HOT0180-1.jpg',
hot: 'HOT180',
title: 'Bayur',
description: 'Schoutenia accrescens (Merr)',
},
{ id : 'HOT181-Ati-ati',
imageUrl: 'assets/imgs/herb/HOT0181-Ati-ati/HOT0181-1.jpg',
hot: 'HOT181',
title: 'Ati-ati',
description: 'Coleus blumei (Benth)',
},
{ id : 'HOT182-Bunga jarum',
imageUrl: 'assets/imgs/herb/HOT0182-Bunga jarum/HOT0182-1.jpg',
hot: 'HOT182',
title: 'Bunga jarum',
description: 'Ixora paludosa Kurz',
},
{ id : 'HOT183-Balek Adap',
imageUrl: 'assets/imgs/herb/HOT0183-Balek Adap/HOT0183-1.jpg',
hot: 'HOT183',
title: 'Balek Adap',
description: 'Mussaenda villosa (Wall.)',
},
{ id : 'HOT184-Bayam Duri Merah',
imageUrl: 'assets/imgs/herb/HOT0184-Bayam Duri Merah/HOT0184-1.jpg',
hot: 'HOT184',
title: 'Bayam Duri Merah',
description: 'Amaranthus spinosus (L)',
},
{ id : 'HOT185-Bemban',
imageUrl: 'assets/imgs/herb/HOT0185-Bemban/HOT0185-1.jpg',
hot: 'HOT185',
title: 'Bemban',
description: 'Donax grandis (Mig). K. Schun.',
},
{ id : 'HOT186-Beluru',
imageUrl: 'assets/imgs/herb/HOT0186-Beluru/HOT0186-1.jpg',
hot: 'HOT186',
title: 'Beluru',
description: 'Entada phaseoloides L (Merr)',
},
{ id : 'HOT187-Bonglai Bukit',
imageUrl: 'assets/imgs/herb/HOT0187-Bonglai Bukit/HOT0187-1.jpg',
hot: 'HOT187',
title: 'Bonglai Bukit',
description: 'Zingiber cassumnar (Robx)',
},
{ id : 'HOT188-Buas-buas',
imageUrl: 'assets/imgs/herb/HOT0188-Buas-buas/HOT0188-1.jpg',
hot: 'HOT188',
title: 'Buas-buas',
description: 'Premna foetida (Reinw).',
},
{ id : 'HOT189-Bunga Cina Susun',
imageUrl: 'assets/imgs/herb/HOT0189-Bunga Cina Susun/HOT0189-1.jpg',
hot: 'HOT189',
title: 'Bunga Cina Susun',
description: 'Gardenia florida (L)',
},
{ id : 'HOT190-Bunga Landak',
imageUrl: 'assets/imgs/herb/HOT0190-Bunga Landak/HOT0190-1.jpg',
hot: 'HOT190',
title: 'Bunga Landak',
description: 'Barleria prionitis L.',
},
{ id : 'HOT191-Celaka Merah',
imageUrl: 'assets/imgs/herb/HOT0191-Celaka Merah/HOT0191-1.jpg',
hot: 'HOT191',
title: 'Celaka Merah',
description: 'Clerodendrum thomsonae',
},
{ id : 'HOT192-Celaka Pangan Biru/Ceraka',
imageUrl: 'assets/imgs/herb/HOT0192-Celaka Pangan Biru/Ceraka/HOT0192-1.jpg',
hot: 'HOT192',
title: 'Celaka Pangan Biru/Ceraka',
description: 'Plumbago zeylanica (L)Synonym : P.viscosa Blanco',
},
{ id : 'HOT193-Chenderai',
imageUrl: 'assets/imgs/herb/HOT0193-Chenderai/HOT0193-1.jpg',
hot: 'HOT193',
title: 'Chenderai',
description: 'Microcos tomentosa (gim) Synonym : Grewia paniculata L.',
},
{ id : 'HOT194-Cili padi',
imageUrl: 'assets/imgs/herb/HOT0194-Cili padi/HOT0194-1.jpg',
hot: 'HOT194',
title: 'Cili padi',
description: 'Capsicum frutescens L.',
},
{ id : 'HOT195-Ekor Tikus',
imageUrl: 'assets/imgs/herb/HOT0195-Ekor Tikus/HOT0195-1.jpg',
hot: 'HOT195',
title: 'Ekor Tikus',
description: 'Stachytarpheta jamaicensis (Vahl.)',
},
{ id : 'HOT196-Gajah Tarik',
imageUrl: 'assets/imgs/herb/HOT0196-Gajah Tarik/HOT0196-1.jpg',
hot: 'HOT196',
title: 'Gajah Tarik',
description: 'Strycnos spp.',
},
{ id : 'HOT197-Gambir-gambir',
imageUrl: 'assets/imgs/herb/HOT0197-Gambir-gambir/HOT0197-1.jpg',
hot: 'HOT197',
title: 'Gambir-gambir',
description: 'Combretum sundaicum (Miq)',
},
{ id : 'HOT198-Gambir Laut',
imageUrl: 'assets/imgs/herb/HOT0198-Gambir Laut/HOT0198-1.jpg',
hot: 'HOT198',
title: 'Gambir Laut',
description: 'Uncaria lanosa (Wall)',
},
{ id : 'HOT199-Gelam Tikus',
imageUrl: 'assets/imgs/herb/HOT0199-Gelam Tikus/HOT0199-1.jpg',
hot: 'HOT199',
title: 'Gelam Tikus',
description: 'Syzygium zeylanicum (wight.)',
},
{ id : 'HOT200-Hujan Panas',
imageUrl: 'assets/imgs/herb/HOT0200-Hujan Panas/HOT0200-1.jpg',
hot: 'HOT200',
title: 'Hujan Panas',
description: 'Croton sp.',
},
{ id : 'HOT201-Gucil',
imageUrl: 'assets/imgs/herb/HOT0201-Gucil/HOT0201-1.jpg',
hot: 'HOT201',
title: 'Gucil',
description: 'Antidesma montanum (Bi)',
},
{ id : 'HOT202-Jarak Belanda',
imageUrl: 'assets/imgs/herb/HOT0202-Jarak Belanda/HOT0202-1.jpg',
hot: 'HOT202',
title: 'Jarak Belanda',
description: 'Jatropha curcas',
},
{ id : 'HOT203-Bisa Ular',
imageUrl: 'assets/imgs/herb/HOT0203-Bisa Ular/HOT0203-1.jpg',
hot: 'HOT203',
title: 'Bisa Ular',
description: 'Barleria lupulina',
},
{ id : 'HOT204-Ara Songsang/rumput israel',
imageUrl: 'assets/imgs/herb/HOT0204-Ara Songsang/rumput israel/HOT0204-1.jpg',
hot: 'HOT204',
title: 'Ara Songsang/rumput israel',
description: 'Asystasia gangetica',
},
{ id : 'HOT205-Balung Ayam',
imageUrl: 'assets/imgs/herb/HOT0205-Balung Ayam/HOT0205-1.jpg',
hot: 'HOT205',
title: 'Balung Ayam',
description: 'Celosia argentea',
},
{ id : 'HOT206-Bawang tanah',
imageUrl: 'assets/imgs/herb/HOT0206-Bawang tanah/HOT0206-1.jpg',
hot: 'HOT206',
title: 'Bawang tanah',
description: 'Hippeastrum reticulatum',
},
{ id : 'HOT207-Bunga tiga bulan/Siti Zubaidah',
imageUrl: 'assets/imgs/herb/HOT0207-Bunga tiga bulan/Siti Zubaidah/HOT0207-1.jpg',
hot: 'HOT207',
title: 'Bunga tiga bulan/Siti Zubaidah',
description: 'Hydrangea macrophylla',
},
{ id : 'HOT208-Butang Baju',
imageUrl: 'assets/imgs/herb/HOT0208-Butang Baju/HOT0208-1.jpg',
hot: 'HOT208',
title: 'Butang Baju',
description: 'Hyptis capitata.Synonym: Hyptis suaveolens',
},
{ id : 'HOT209-Dedalu cina',
imageUrl: 'assets/imgs/herb/HOT0209-Dedalu cina/HOT0209-1.jpg',
hot: 'HOT209',
title: 'Dedalu cina',
description: 'Laurentia longoflora',
},
{ id : 'HOT210-Hempedu Beruang',
imageUrl: 'assets/imgs/herb/HOT0210-Hempedu Beruang/HOT0210-1.jpg',
hot: 'HOT210',
title: 'Hempedu Beruang',
description: 'Thottea grandilfora',
}, /*
{ id : 'HOT211-Kerbau Amok',
imageUrl: 'assets/imgs/herb/HOT0211-Kerbau Amok/HOT0211-1.jpg',
hot: 'HOT211',
title: 'Kerbau Amok',
description: 'Schefflera ridleyi',
},
{ id : 'HOT212-Lemba',
imageUrl: 'assets/imgs/herb/HOT0212-Lemba/HOT0212-1.jpg',
hot: 'HOT212',
title: 'Lemba',
description: 'Molineria latifolia',
},
{ id : 'HOT213-Lempoyang Hitam',
imageUrl: 'assets/imgs/herb/HOT0213-Lempoyang Hitam/HOT0213-1.jpg',
hot: 'HOT213',
title: 'Lempoyang Hitam',
description: 'Zingiber ottensini',
},
{ id : 'HOT214-Lidah Jin',
imageUrl: 'assets/imgs/herb/HOT0214-Lidah Jin/HOT0214-1.jpg',
hot: 'HOT214',
title: 'Lidah Jin',
description: 'Sansevieria trifasciata',
},
{ id : 'HOT215-Lidah jin Kuning',
imageUrl: 'assets/imgs/herb/HOT0215-Lidah jin Kuning/HOT0215-1.jpg',
hot: 'HOT215',
title: 'Lidah jin Kuning',
description: 'Sansevieria trifasciata "Laurentii"',
},
{ id : 'HOT216-Lidah Naga',
imageUrl: 'assets/imgs/herb/HOT0216-Lidah Naga/HOT0216-1.jpg',
hot: 'HOT216',
title: 'Lidah Naga',
description: 'Sauropus rostratus',
},
{ id : 'HOT217-Memali',
imageUrl: 'assets/imgs/herb/HOT0217-Memali/HOT0217-1.jpg',
hot: 'HOT217',
title: 'Memali',
description: 'Leea aculeata',
},
{ id : 'HOT218-Mengkuang Hijau',
imageUrl: 'assets/imgs/herb/HOT0218-Mengkuang Hijau/HOT0218-1.jpg',
hot: 'HOT218',
title: 'Mengkuang Hijau',
description: 'Pandanus pygmaeus',
},
{ id : 'HOT219-Nenas batu',
imageUrl: 'assets/imgs/herb/HOT0219-Nenas batu/HOT0219-1.jpg',
hot: 'HOT219',
title: 'Nenas batu',
description: 'Ananas sp',
},
{ id : 'HOT220-Nyonya makan Sireh',
imageUrl: 'assets/imgs/herb/HOT0220-Nyonya makan Sireh/HOT0220-1.jpg',
hot: 'HOT220',
title: 'Nyonya makan Sireh',
description: 'Clerodendron thomsonae',
},
{ id : 'HOT221-Pegaga Bukit',
imageUrl: 'assets/imgs/herb/HOT0221-Pegaga Bukit/HOT0221-1.jpg',
hot: 'HOT221',
title: 'Pegaga Bukit',
description: 'Centella asiatica',
},
{ id : 'HOT222-Pisang Tali',
imageUrl: 'assets/imgs/herb/HOT0222-Pisang Tali/HOT0222-1.jpg',
hot: 'HOT222',
title: 'Pisang Tali',
description: 'Heloconia rostrata',
},
{ id : 'HOT223-Mempelam',
imageUrl: 'assets/imgs/herb/HOT0223-Mempelam/HOT0223-1.jpg',
hot: 'HOT223',
title: 'Mempelam',
description: 'Mangifera indica',
},
{ id : 'HOT224-Bakung',
imageUrl: 'assets/imgs/herb/HOT0224-Bakung/HOT0224-1.jpg',
hot: 'HOT224',
title: 'Bakung',
description: 'Hymenocallis littoralis',
},
{ id : 'HOT225-Payung Ali',
imageUrl: 'assets/imgs/herb/HOT0225-Payung Ali/HOT0225-1.jpg',
hot: 'HOT225',
title: 'Payung Ali',
description: 'Cyperus involucratus',
},
{ id : 'HOT226-Raja Santung Tanah',
imageUrl: 'assets/imgs/herb/HOT0226-Raja Santung Tanah/HOT0226-1.jpg',
hot: 'HOT226',
title: 'Raja Santung Tanah',
description: 'Aphelandra squarrosa',
},
{ id : 'HOT227-Rumput Teki',
imageUrl: 'assets/imgs/herb/HOT0227-Rumput Teki/HOT0227-1.jpg',
hot: 'HOT227',
title: 'Rumput Teki',
description: 'Kyllinga brevifolia Rottb.',
},
{ id : 'HOT228-Bunga kertas',
imageUrl: 'assets/imgs/herb/HOT0228-Bunga kertas/HOT0228-1.jpg',
hot: 'HOT228',
title: 'Bunga kertas',
description: 'Bougainvillea glabra Choisy',
},
{ id : 'HOT229-Malinja',
imageUrl: 'assets/imgs/herb/HOT0229-Malinja/HOT0229-1.jpg',
hot: 'HOT229',
title: 'Malinja',
description: 'Gnetum gnemon',
},
{ id : 'HOT230-Tepus tanah',
imageUrl: 'assets/imgs/herb/HOT0230-Tepus tanah/HOT0230-1.jpg',
hot: 'HOT230',
title: 'Tepus tanah',
description: 'Alpinia mutica',
},
{ id : 'HOT231-Sagu Burma',
imageUrl: 'assets/imgs/herb/HOT0231-Sagu Burma/HOT0231-1.jpg',
hot: 'HOT231',
title: 'Sagu Burma',
description: 'Maranta arundinacea',
},
{ id : 'HOT232-Sambang Merah',
imageUrl: 'assets/imgs/herb/HOT0232-Sambang Merah/HOT0232-1.jpg',
hot: 'HOT232',
title: 'Sambang Merah',
description: 'Excoecaria cochinchinensis Lour.',
},
{ id : 'HOT233-Tapak itik/setawar kampung',
imageUrl: 'assets/imgs/herb/HOT0233-Tapak itik/setawar kampung/HOT0233-1.jpg',
hot: 'HOT233',
title: 'Tapak itik/setawar kampung',
description: 'Kalanchoe lacinata',
},
{ id : 'HOT234-Tapak Rimau',
imageUrl: 'assets/imgs/herb/HOT0234-Tapak Rimau/HOT0234-1.jpg',
hot: 'HOT234',
title: 'Tapak Rimau',
description: 'Trevasia burckii',
},
{ id : 'HOT235-Tempuyung',
imageUrl: 'assets/imgs/herb/HOT0235-Tempuyung/HOT0235-1.jpg',
hot: 'HOT235',
title: 'Tempuyung',
description: 'Sonchus arvensis L.',
},
{ id : 'HOT236-Terung Susu Kambing',
imageUrl: 'assets/imgs/herb/HOT0236-Terung Susu Kambing/HOT0236-1.jpg',
hot: 'HOT236',
title: 'Terung Susu Kambing',
description: 'Solanum mammosum L.',
},
{ id : 'HOT237-Vanila',
imageUrl: 'assets/imgs/herb/HOT0237-Vanila/HOT0237-1.jpg',
hot: 'HOT237',
title: 'Vanila',
description: 'Vanilla planifolia',
}, */
  ];

  viewEntry(param : any) : void
   {
      this.navCtrl.push('SpecificPage', param);
   }

  /*  sort(){
    this.descending = !this.descending;
    this.order = this.descending ? 1 : -1;
  } */



/* Amir Fitri - Yang ni untuk function dalam three dots*/
presentPopover(myEvent) {
  let popover = this.popoverCtrl.create(PopoverPage);
  popover.present({
    ev: myEvent
  });
}




  /* Min  */
  sort(){
    this.lists.sort(function(a, b) {
      var textA = a.title.toUpperCase();
      var textB = b.title.toUpperCase();
      return (textA < textB) ? -1 : (textA > textB) ? 1 : 0;
  });
  console.log(this.lists);
  this.tsutsun='huruf';
  }
  
   /* Min  */
   sort2(){
    this.lists.sort(function(a, b) {
      var textA = a.hot.toUpperCase();
      var textB = b.hot.toUpperCase();
      return (textA < textB) ? -1 : (textA > textB) ? 1 : 0;
  });
  console.log(this.lists);
  this.tsutsun='kod';
  }

}

